export const listOptions = [
  { value: 'A', label: 'A' },
  { value: 'B', label: 'B' },
  { value: 'C', label: 'C' },
  { value: 'D', label: 'D' },
];

export const selectStyle = {
  singleValue: (baseStyles, state) => ({
    ...baseStyles,
    color: 'black',
    fontWeight: '550',
  }),
  optionsSelect: (baseStyles, state) => ({
    ...baseStyles,
    color: 'black',
    fontWeight: '550',
  }),
  option: (baseStyles, state) => ({
    ...baseStyles,
    color: 'black',
    fontWeight: '550',
  }),
  placeholder: (baseStyles, state) => ({
    ...baseStyles,
    color: '#777777',
    fontWeight: '550',
  }),
  noOptionsMessage: (baseStyles, state) => ({
    ...baseStyles,
    color: 'black',
    fontWeight: '550',
  }),
  input: (baseStyles, state) => ({
    ...baseStyles,
    color: 'black',
    fontWeight: '550',
  }),
};

export const listBank = [
  { label: 'Ngân hàng VIB', value: 'Ngân hàng VIB' },
  { label: 'Ngân hàng VIETCAPITAL', value: 'Ngân hàng VIETCAPITAL' },
  { label: 'Ngân hàng SCB', value: 'Ngân hàng SCB' },
  { label: 'Ngân hàng NCB', value: 'Ngân hàng NCB' },
  { label: 'Ngân hàng Sacombank', value: 'Ngân hàng Sacombank' },
  { label: 'Ngân hàng EximBank', value: 'Ngân hàng EximBank' },
  { label: 'Ngân hàng MSBank', value: 'Ngân hàng MSBank' },
  { label: 'Ngân hàng NamABank', value: 'Ngân hàng NamABank' },
  { label: 'Ngân hàng VietinBank', value: 'Ngân hàng VietinBank' },
  { label: 'Ngân hàng VCB', value: 'Ngân hàng VCB' },
  { label: 'Ngân hàng HDBank', value: 'Ngân hàng HDBank' },
  { label: 'Ngân hàng Đông Á', value: 'Ngân hàng Đông Á' },
  { label: 'Ngân hàng TP Bank', value: 'Ngân hàng TP Bank' },
  { label: 'Ngân hàng OceanBank', value: 'Ngân hàng OceanBank' },
  { label: 'Ngân hàng BIDV', value: 'Ngân hàng BIDV' },
  { label: 'Ngân hàng Techcombank', value: 'Ngân hàng Techcombank' },
  { label: 'Ngân hàng VPBank', value: 'Ngân hàng VPBank' },
  { label: 'Ngân hàng Agribank', value: 'Ngân hàng Agribank' },
  { label: 'Ngân hàng MBBank', value: 'Ngân hàng MBBank' },
  { label: 'Ngân hàng ACB', value: 'Ngân hàng ACB' },
  { label: 'Ngân hàng OCB', value: 'Ngân hàng OCB' },
  { label: 'Ngân hàng IVB', value: 'Ngân hàng IVB' },
  { label: 'Ngân hàng SHB', value: 'Ngân hàng SHB' },
];

export const vnListPhone = [
  '088',
  '091',
  '094',
  '083',
  '084',
  '085',
  '081',
  '082',
  '086',
  '096',
  '097',
  '098',
  '032',
  '033',
  '034',
  '035',
  '036',
  '037',
  '038',
  '039',
  '089',
  '090',
  '093',
  '070',
  '079',
  '077',
  '076',
  '078',
  '092',
  '056',
  '058',
  '099',
  '059',
  '087',
];
